# Site settings
title: 
header-img: img/home-bg.png
email: thurman024@gmail.com
copyright_name: thurman024
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  thurman024
learn_profile: thurman024
email_username: thurman024@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
